# syntax=docker/dockerfile:1
FROM alpine:3 as base
RUN apk add --no-cache nodejs yarn npm python3 openssl build-base
WORKDIR /app
ENV NODE_ENV=production
COPY yarn.lock package.json ./
RUN npm rebuild bcrypt --build-from-source && \
    yarn install --production

FROM alpine:3 as prod
RUN apk add --no-cache nodejs yarn openssl tini
WORKDIR /app
COPY --from=base /app /app
ADD . .
ENTRYPOINT ["/sbin/tini","-g",  "--"]
CMD ["node", "app.js"]
