version: '3'
services:
  actual_server:
    image: jlongster/actual-server:latest
    ports:
      - 5006:5006
    environment:
      # Add or change configuration options here.
      - ACTUAL_SERVER_FILES=/data/server-files
      - ACTUAL_USER_FILES=/data/user-files
    volumes:
      - ./server-data:/data
    restart: unless-stopped
