version: "3"
services:
  actual_server:
    container_name: actual_server
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5006:5006"
    volumes:
      - ./data:/data
    restart: unless-stopped
