app = "%NAME%"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = "5006"
  TINI_SUBREAPER = 1

[experimental]
  allowed_public_ports = []
  auto_rollback = true
  cmd = ["node", "--max-old-space-size=180", "app.js"]

[[services]]
  http_checks = []
  internal_port = 5006
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "10s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
