name: Feature request
description: Request a missing feature
title: '[Feature] '
labels: ['feature']
body:
  - type: markdown
    id: intro-md
    attributes:
      value: |
        Please use the main Actual repository to make feature requests. This can be done here:
        https://github.com/actualbudget/actual/issues/new/choose
