name: Build Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push standard image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKERHUB_PROJECT }}:latest

      - name: Build and push Alpine image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: Dockerfile.alpine
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKERHUB_PROJECT }}:alpine
